# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/postaron/CLionProjects/CHPS0731

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/postaron/CLionProjects/CHPS0731

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/postaron/CLionProjects/CHPS0731/CMakeFiles /home/postaron/CLionProjects/CHPS0731/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/postaron/CLionProjects/CHPS0731/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named RayTrace

# Build rule for target.
RayTrace: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 RayTrace
.PHONY : RayTrace

# fast build rule for target.
RayTrace/fast:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/build
.PHONY : RayTrace/fast

Camera/camera.o: Camera/camera.cpp.o

.PHONY : Camera/camera.o

# target to build an object file
Camera/camera.cpp.o:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/Camera/camera.cpp.o
.PHONY : Camera/camera.cpp.o

Camera/camera.i: Camera/camera.cpp.i

.PHONY : Camera/camera.i

# target to preprocess a source file
Camera/camera.cpp.i:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/Camera/camera.cpp.i
.PHONY : Camera/camera.cpp.i

Camera/camera.s: Camera/camera.cpp.s

.PHONY : Camera/camera.s

# target to generate assembly for a file
Camera/camera.cpp.s:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/Camera/camera.cpp.s
.PHONY : Camera/camera.cpp.s

Camera/rayon.o: Camera/rayon.cpp.o

.PHONY : Camera/rayon.o

# target to build an object file
Camera/rayon.cpp.o:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/Camera/rayon.cpp.o
.PHONY : Camera/rayon.cpp.o

Camera/rayon.i: Camera/rayon.cpp.i

.PHONY : Camera/rayon.i

# target to preprocess a source file
Camera/rayon.cpp.i:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/Camera/rayon.cpp.i
.PHONY : Camera/rayon.cpp.i

Camera/rayon.s: Camera/rayon.cpp.s

.PHONY : Camera/rayon.s

# target to generate assembly for a file
Camera/rayon.cpp.s:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/Camera/rayon.cpp.s
.PHONY : Camera/rayon.cpp.s

Camera/scene.o: Camera/scene.cpp.o

.PHONY : Camera/scene.o

# target to build an object file
Camera/scene.cpp.o:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/Camera/scene.cpp.o
.PHONY : Camera/scene.cpp.o

Camera/scene.i: Camera/scene.cpp.i

.PHONY : Camera/scene.i

# target to preprocess a source file
Camera/scene.cpp.i:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/Camera/scene.cpp.i
.PHONY : Camera/scene.cpp.i

Camera/scene.s: Camera/scene.cpp.s

.PHONY : Camera/scene.s

# target to generate assembly for a file
Camera/scene.cpp.s:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/Camera/scene.cpp.s
.PHONY : Camera/scene.cpp.s

Image/image.o: Image/image.cpp.o

.PHONY : Image/image.o

# target to build an object file
Image/image.cpp.o:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/Image/image.cpp.o
.PHONY : Image/image.cpp.o

Image/image.i: Image/image.cpp.i

.PHONY : Image/image.i

# target to preprocess a source file
Image/image.cpp.i:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/Image/image.cpp.i
.PHONY : Image/image.cpp.i

Image/image.s: Image/image.cpp.s

.PHONY : Image/image.s

# target to generate assembly for a file
Image/image.cpp.s:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/Image/image.cpp.s
.PHONY : Image/image.cpp.s

Lights/light.o: Lights/light.cpp.o

.PHONY : Lights/light.o

# target to build an object file
Lights/light.cpp.o:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/Lights/light.cpp.o
.PHONY : Lights/light.cpp.o

Lights/light.i: Lights/light.cpp.i

.PHONY : Lights/light.i

# target to preprocess a source file
Lights/light.cpp.i:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/Lights/light.cpp.i
.PHONY : Lights/light.cpp.i

Lights/light.s: Lights/light.cpp.s

.PHONY : Lights/light.s

# target to generate assembly for a file
Lights/light.cpp.s:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/Lights/light.cpp.s
.PHONY : Lights/light.cpp.s

Lights/plan_light.o: Lights/plan_light.cpp.o

.PHONY : Lights/plan_light.o

# target to build an object file
Lights/plan_light.cpp.o:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/Lights/plan_light.cpp.o
.PHONY : Lights/plan_light.cpp.o

Lights/plan_light.i: Lights/plan_light.cpp.i

.PHONY : Lights/plan_light.i

# target to preprocess a source file
Lights/plan_light.cpp.i:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/Lights/plan_light.cpp.i
.PHONY : Lights/plan_light.cpp.i

Lights/plan_light.s: Lights/plan_light.cpp.s

.PHONY : Lights/plan_light.s

# target to generate assembly for a file
Lights/plan_light.cpp.s:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/Lights/plan_light.cpp.s
.PHONY : Lights/plan_light.cpp.s

Materials/material.o: Materials/material.cpp.o

.PHONY : Materials/material.o

# target to build an object file
Materials/material.cpp.o:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/Materials/material.cpp.o
.PHONY : Materials/material.cpp.o

Materials/material.i: Materials/material.cpp.i

.PHONY : Materials/material.i

# target to preprocess a source file
Materials/material.cpp.i:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/Materials/material.cpp.i
.PHONY : Materials/material.cpp.i

Materials/material.s: Materials/material.cpp.s

.PHONY : Materials/material.s

# target to generate assembly for a file
Materials/material.cpp.s:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/Materials/material.cpp.s
.PHONY : Materials/material.cpp.s

Materials/perlin.o: Materials/perlin.cpp.o

.PHONY : Materials/perlin.o

# target to build an object file
Materials/perlin.cpp.o:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/Materials/perlin.cpp.o
.PHONY : Materials/perlin.cpp.o

Materials/perlin.i: Materials/perlin.cpp.i

.PHONY : Materials/perlin.i

# target to preprocess a source file
Materials/perlin.cpp.i:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/Materials/perlin.cpp.i
.PHONY : Materials/perlin.cpp.i

Materials/perlin.s: Materials/perlin.cpp.s

.PHONY : Materials/perlin.s

# target to generate assembly for a file
Materials/perlin.cpp.s:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/Materials/perlin.cpp.s
.PHONY : Materials/perlin.cpp.s

Materials/phong.o: Materials/phong.cpp.o

.PHONY : Materials/phong.o

# target to build an object file
Materials/phong.cpp.o:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/Materials/phong.cpp.o
.PHONY : Materials/phong.cpp.o

Materials/phong.i: Materials/phong.cpp.i

.PHONY : Materials/phong.i

# target to preprocess a source file
Materials/phong.cpp.i:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/Materials/phong.cpp.i
.PHONY : Materials/phong.cpp.i

Materials/phong.s: Materials/phong.cpp.s

.PHONY : Materials/phong.s

# target to generate assembly for a file
Materials/phong.cpp.s:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/Materials/phong.cpp.s
.PHONY : Materials/phong.cpp.s

Materials/texture.o: Materials/texture.cpp.o

.PHONY : Materials/texture.o

# target to build an object file
Materials/texture.cpp.o:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/Materials/texture.cpp.o
.PHONY : Materials/texture.cpp.o

Materials/texture.i: Materials/texture.cpp.i

.PHONY : Materials/texture.i

# target to preprocess a source file
Materials/texture.cpp.i:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/Materials/texture.cpp.i
.PHONY : Materials/texture.cpp.i

Materials/texture.s: Materials/texture.cpp.s

.PHONY : Materials/texture.s

# target to generate assembly for a file
Materials/texture.cpp.s:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/Materials/texture.cpp.s
.PHONY : Materials/texture.cpp.s

Objects/Mesh/GeometricModel.o: Objects/Mesh/GeometricModel.cpp.o

.PHONY : Objects/Mesh/GeometricModel.o

# target to build an object file
Objects/Mesh/GeometricModel.cpp.o:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/Objects/Mesh/GeometricModel.cpp.o
.PHONY : Objects/Mesh/GeometricModel.cpp.o

Objects/Mesh/GeometricModel.i: Objects/Mesh/GeometricModel.cpp.i

.PHONY : Objects/Mesh/GeometricModel.i

# target to preprocess a source file
Objects/Mesh/GeometricModel.cpp.i:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/Objects/Mesh/GeometricModel.cpp.i
.PHONY : Objects/Mesh/GeometricModel.cpp.i

Objects/Mesh/GeometricModel.s: Objects/Mesh/GeometricModel.cpp.s

.PHONY : Objects/Mesh/GeometricModel.s

# target to generate assembly for a file
Objects/Mesh/GeometricModel.cpp.s:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/Objects/Mesh/GeometricModel.cpp.s
.PHONY : Objects/Mesh/GeometricModel.cpp.s

Objects/Mesh/OBJLoader.o: Objects/Mesh/OBJLoader.cpp.o

.PHONY : Objects/Mesh/OBJLoader.o

# target to build an object file
Objects/Mesh/OBJLoader.cpp.o:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/Objects/Mesh/OBJLoader.cpp.o
.PHONY : Objects/Mesh/OBJLoader.cpp.o

Objects/Mesh/OBJLoader.i: Objects/Mesh/OBJLoader.cpp.i

.PHONY : Objects/Mesh/OBJLoader.i

# target to preprocess a source file
Objects/Mesh/OBJLoader.cpp.i:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/Objects/Mesh/OBJLoader.cpp.i
.PHONY : Objects/Mesh/OBJLoader.cpp.i

Objects/Mesh/OBJLoader.s: Objects/Mesh/OBJLoader.cpp.s

.PHONY : Objects/Mesh/OBJLoader.s

# target to generate assembly for a file
Objects/Mesh/OBJLoader.cpp.s:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/Objects/Mesh/OBJLoader.cpp.s
.PHONY : Objects/Mesh/OBJLoader.cpp.s

Objects/Mesh/bounding_box.o: Objects/Mesh/bounding_box.cpp.o

.PHONY : Objects/Mesh/bounding_box.o

# target to build an object file
Objects/Mesh/bounding_box.cpp.o:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/Objects/Mesh/bounding_box.cpp.o
.PHONY : Objects/Mesh/bounding_box.cpp.o

Objects/Mesh/bounding_box.i: Objects/Mesh/bounding_box.cpp.i

.PHONY : Objects/Mesh/bounding_box.i

# target to preprocess a source file
Objects/Mesh/bounding_box.cpp.i:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/Objects/Mesh/bounding_box.cpp.i
.PHONY : Objects/Mesh/bounding_box.cpp.i

Objects/Mesh/bounding_box.s: Objects/Mesh/bounding_box.cpp.s

.PHONY : Objects/Mesh/bounding_box.s

# target to generate assembly for a file
Objects/Mesh/bounding_box.cpp.s:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/Objects/Mesh/bounding_box.cpp.s
.PHONY : Objects/Mesh/bounding_box.cpp.s

Objects/Mesh/mesh.o: Objects/Mesh/mesh.cpp.o

.PHONY : Objects/Mesh/mesh.o

# target to build an object file
Objects/Mesh/mesh.cpp.o:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/Objects/Mesh/mesh.cpp.o
.PHONY : Objects/Mesh/mesh.cpp.o

Objects/Mesh/mesh.i: Objects/Mesh/mesh.cpp.i

.PHONY : Objects/Mesh/mesh.i

# target to preprocess a source file
Objects/Mesh/mesh.cpp.i:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/Objects/Mesh/mesh.cpp.i
.PHONY : Objects/Mesh/mesh.cpp.i

Objects/Mesh/mesh.s: Objects/Mesh/mesh.cpp.s

.PHONY : Objects/Mesh/mesh.s

# target to generate assembly for a file
Objects/Mesh/mesh.cpp.s:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/Objects/Mesh/mesh.cpp.s
.PHONY : Objects/Mesh/mesh.cpp.s

Objects/objet.o: Objects/objet.cpp.o

.PHONY : Objects/objet.o

# target to build an object file
Objects/objet.cpp.o:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/Objects/objet.cpp.o
.PHONY : Objects/objet.cpp.o

Objects/objet.i: Objects/objet.cpp.i

.PHONY : Objects/objet.i

# target to preprocess a source file
Objects/objet.cpp.i:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/Objects/objet.cpp.i
.PHONY : Objects/objet.cpp.i

Objects/objet.s: Objects/objet.cpp.s

.PHONY : Objects/objet.s

# target to generate assembly for a file
Objects/objet.cpp.s:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/Objects/objet.cpp.s
.PHONY : Objects/objet.cpp.s

Objects/plan.o: Objects/plan.cpp.o

.PHONY : Objects/plan.o

# target to build an object file
Objects/plan.cpp.o:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/Objects/plan.cpp.o
.PHONY : Objects/plan.cpp.o

Objects/plan.i: Objects/plan.cpp.i

.PHONY : Objects/plan.i

# target to preprocess a source file
Objects/plan.cpp.i:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/Objects/plan.cpp.i
.PHONY : Objects/plan.cpp.i

Objects/plan.s: Objects/plan.cpp.s

.PHONY : Objects/plan.s

# target to generate assembly for a file
Objects/plan.cpp.s:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/Objects/plan.cpp.s
.PHONY : Objects/plan.cpp.s

Objects/sphere.o: Objects/sphere.cpp.o

.PHONY : Objects/sphere.o

# target to build an object file
Objects/sphere.cpp.o:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/Objects/sphere.cpp.o
.PHONY : Objects/sphere.cpp.o

Objects/sphere.i: Objects/sphere.cpp.i

.PHONY : Objects/sphere.i

# target to preprocess a source file
Objects/sphere.cpp.i:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/Objects/sphere.cpp.i
.PHONY : Objects/sphere.cpp.i

Objects/sphere.s: Objects/sphere.cpp.s

.PHONY : Objects/sphere.s

# target to generate assembly for a file
Objects/sphere.cpp.s:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/Objects/sphere.cpp.s
.PHONY : Objects/sphere.cpp.s

Objects/triangle.o: Objects/triangle.cpp.o

.PHONY : Objects/triangle.o

# target to build an object file
Objects/triangle.cpp.o:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/Objects/triangle.cpp.o
.PHONY : Objects/triangle.cpp.o

Objects/triangle.i: Objects/triangle.cpp.i

.PHONY : Objects/triangle.i

# target to preprocess a source file
Objects/triangle.cpp.i:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/Objects/triangle.cpp.i
.PHONY : Objects/triangle.cpp.i

Objects/triangle.s: Objects/triangle.cpp.s

.PHONY : Objects/triangle.s

# target to generate assembly for a file
Objects/triangle.cpp.s:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/Objects/triangle.cpp.s
.PHONY : Objects/triangle.cpp.s

intersection.o: intersection.cpp.o

.PHONY : intersection.o

# target to build an object file
intersection.cpp.o:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/intersection.cpp.o
.PHONY : intersection.cpp.o

intersection.i: intersection.cpp.i

.PHONY : intersection.i

# target to preprocess a source file
intersection.cpp.i:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/intersection.cpp.i
.PHONY : intersection.cpp.i

intersection.s: intersection.cpp.s

.PHONY : intersection.s

# target to generate assembly for a file
intersection.cpp.s:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/intersection.cpp.s
.PHONY : intersection.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/main.cpp.s
.PHONY : main.cpp.s

png/lodepng.o: png/lodepng.cpp.o

.PHONY : png/lodepng.o

# target to build an object file
png/lodepng.cpp.o:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/png/lodepng.cpp.o
.PHONY : png/lodepng.cpp.o

png/lodepng.i: png/lodepng.cpp.i

.PHONY : png/lodepng.i

# target to preprocess a source file
png/lodepng.cpp.i:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/png/lodepng.cpp.i
.PHONY : png/lodepng.cpp.i

png/lodepng.s: png/lodepng.cpp.s

.PHONY : png/lodepng.s

# target to generate assembly for a file
png/lodepng.cpp.s:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/png/lodepng.cpp.s
.PHONY : png/lodepng.cpp.s

post_process.o: post_process.cpp.o

.PHONY : post_process.o

# target to build an object file
post_process.cpp.o:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/post_process.cpp.o
.PHONY : post_process.cpp.o

post_process.i: post_process.cpp.i

.PHONY : post_process.i

# target to preprocess a source file
post_process.cpp.i:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/post_process.cpp.i
.PHONY : post_process.cpp.i

post_process.s: post_process.cpp.s

.PHONY : post_process.s

# target to generate assembly for a file
post_process.cpp.s:
	$(MAKE) -f CMakeFiles/RayTrace.dir/build.make CMakeFiles/RayTrace.dir/post_process.cpp.s
.PHONY : post_process.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... RayTrace"
	@echo "... edit_cache"
	@echo "... Camera/camera.o"
	@echo "... Camera/camera.i"
	@echo "... Camera/camera.s"
	@echo "... Camera/rayon.o"
	@echo "... Camera/rayon.i"
	@echo "... Camera/rayon.s"
	@echo "... Camera/scene.o"
	@echo "... Camera/scene.i"
	@echo "... Camera/scene.s"
	@echo "... Image/image.o"
	@echo "... Image/image.i"
	@echo "... Image/image.s"
	@echo "... Lights/light.o"
	@echo "... Lights/light.i"
	@echo "... Lights/light.s"
	@echo "... Lights/plan_light.o"
	@echo "... Lights/plan_light.i"
	@echo "... Lights/plan_light.s"
	@echo "... Materials/material.o"
	@echo "... Materials/material.i"
	@echo "... Materials/material.s"
	@echo "... Materials/perlin.o"
	@echo "... Materials/perlin.i"
	@echo "... Materials/perlin.s"
	@echo "... Materials/phong.o"
	@echo "... Materials/phong.i"
	@echo "... Materials/phong.s"
	@echo "... Materials/texture.o"
	@echo "... Materials/texture.i"
	@echo "... Materials/texture.s"
	@echo "... Objects/Mesh/GeometricModel.o"
	@echo "... Objects/Mesh/GeometricModel.i"
	@echo "... Objects/Mesh/GeometricModel.s"
	@echo "... Objects/Mesh/OBJLoader.o"
	@echo "... Objects/Mesh/OBJLoader.i"
	@echo "... Objects/Mesh/OBJLoader.s"
	@echo "... Objects/Mesh/bounding_box.o"
	@echo "... Objects/Mesh/bounding_box.i"
	@echo "... Objects/Mesh/bounding_box.s"
	@echo "... Objects/Mesh/mesh.o"
	@echo "... Objects/Mesh/mesh.i"
	@echo "... Objects/Mesh/mesh.s"
	@echo "... Objects/objet.o"
	@echo "... Objects/objet.i"
	@echo "... Objects/objet.s"
	@echo "... Objects/plan.o"
	@echo "... Objects/plan.i"
	@echo "... Objects/plan.s"
	@echo "... Objects/sphere.o"
	@echo "... Objects/sphere.i"
	@echo "... Objects/sphere.s"
	@echo "... Objects/triangle.o"
	@echo "... Objects/triangle.i"
	@echo "... Objects/triangle.s"
	@echo "... intersection.o"
	@echo "... intersection.i"
	@echo "... intersection.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... png/lodepng.o"
	@echo "... png/lodepng.i"
	@echo "... png/lodepng.s"
	@echo "... post_process.o"
	@echo "... post_process.i"
	@echo "... post_process.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

